### ISSUE TITLE
Question: Is the gateway still being released as a Docker image?

### ISSUE THREAD

**Issue by jaller94** [WebThingsIO/docs#29]
For developing addons I like the Docker image a lot. I noticed that the repo is archived, so should the Getting Started Guide be removed or marked as deprecated?

https://github.com/WebThingsIO/docs/blob/90cfed8f18f9f2bf134c2a6a590ff97ce3b0a553/README.md?plain=1#L11

**Comment by benfrancis** [comment]
As I understand it the Docker stuff was just merged into the main repo so we should probably just change that link to https://github.com/WebThingsIO/gateway/blob/master/README.docker.md

PRs welcome!
